version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: some_root
      POSTGRES_DB: guitar_shop_api